import { StyleSheet } from 'react-native';
export default StyleSheet.create({
  main_container: {
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  avatar: {
    marginTop: 30,
    width: 100,
    height: 100,
    borderRadius: 80,
  },
  details_list: {
    margin: 10,
    padding: 5,
    minHeight: '70%',
    width: '80%',
    justifyContent: 'space-between',
  },
  details_list_item: {
    fontSize: 20,
    paddingVertical: 5,
    backgroundColor: 'white',
    color: '#386641',
    fontWeight: '500',
    padding: 5,
    borderRadius: 10,
  },
  details_list_name: {
    fontSize: 25,
    paddingVertical: 5,
    color: '#386641',
    fontWeight: '700',
    padding: 5,
    borderRadius: 10,
  },
  details_list_userType: {
    color: 'red',
    marginTop: 4,
    fontSize: 17,
    marginRight: 30,
    color: '#bc4749',
    opacity: 0.9,
    fontWeight: '600',
  },
  details_list_header: {
    fontSize: 15,
    fontWeight: '600',
    paddingLeft: 5,
    opacity: 0.85,
    color: '#bc4749',
  },
  details_list_item_bio: {
    fontSize: 20,
    paddingVertical: 5,
    backgroundColor: 'white',
    color: '#386641',
    fontWeight: '500',
    padding: 5,
    borderRadius: 10,
    marginBottom: 20,
  },
  bio_scrollview: {
    backgroundColor: 'white',
  },
  header_info: {
    marginVertical: 5,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  list_detail_contain: {
    marginVertical: 5,
  },
  header_info_map: {
    marginVertical: 5,
    display: 'flex',
    flexDirection: 'row',
  },
  map_img: {
    width: 35,
    height: 35,
  },
  details_list_edit: {
    marginLeft: 4,
    fontSize: 20,
    fontWeight: '600',
    opacity: 0.85,
    color: '#bc4749',
    paddingLeft: 2,
  },
});
